version: '3.8'

services:
  charge_request_service:
    build: ./charge_request_service
    ports:
      - "5000:5000"
    depends_on:
      - load_balancer

  load_balancer:
    build: ./load_balancer
    ports:
      - "5002:5002"
    depends_on:
      - substation1
      - substation2

  substation1:
    build: ./substation_service
    ports:
      - "8001:8000"
    container_name: substation1

  substation2:
    build: ./substation_service
    ports:
      - "8002:8000"
    container_name: substation2

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
